In [5]:
import numpy as np
import sys

s=range(1000)
print("Size of each element of list in bytes : ",sys.getsizeof(s))
print("Size of whole list in bytes : ",sys.getsizeof(s)*len(s))

d=np.arange(1000)

print("Size of each element of numpy array in bytes : ",d.itemsize)
print("Size of whole numpy array in bytes : ", d.size*d.itemsize)

Size of each element of list in bytes :  48
Size of whole list in bytes :  48000
Size of each element of numpy array in bytes :  4
Size of whole numpy array in bytes :  4000


In [11]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)
print(type(x))
print(x.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [12]:
import numpy as np
arr=np.array(42)
print(arr)
print(type(arr))
print(arr.ndim)

42
<class 'numpy.ndarray'>
0


In [13]:
import numpy as np
x1=np.array([[1,2,3,4]])
print(x1)
print(type(x1))
print(x1.ndim)

[[1 2 3 4]]
<class 'numpy.ndarray'>
2


In [14]:
print(x1[0,2])

3


In [15]:
import numpy as np
x2=np.array([[[1,2,3,4]]])
print(x2)
print(type(x2))
print(x2.ndim)
print(x2[0,0,2])

[[[1 2 3 4]]]
<class 'numpy.ndarray'>
3
3


In [16]:
import numpy as np
x1=np.array([[1,2,3,4],[5,6,7,8]])
print(x1)
print(type(x1))
print(x1.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [18]:
print(x1[1,2])

7


In [21]:
import numpy as np
x1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x1)
print(type(x1))
print(x1.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
<class 'numpy.ndarray'>
3


In [22]:
print(x1[1,1,1])

11


In [24]:
print(x1[1,1,0]+x1[0,1,2])

16


In [25]:
print(x1[0])

[[1 2 3]
 [4 5 6]]


In [26]:
print(x1[0,1])

[4 5 6]


In [27]:
print(x1[0,1,3])

IndexError: index 3 is out of bounds for axis 2 with size 3

In [28]:
print(x1[1,-1])

[10 11 12]


In [29]:
import numpy as np
x1=np.array([[1,2,3,4],[5,6,7,8]])
print(x1)
print(type(x1))
print(x1.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2


In [30]:
print(x1[1,-1])

8


In [31]:
print(x1[-2,-2])

3


In [32]:
print(x1[1,0:3])

[5 6 7]


In [33]:
print(x1[1:,0:3])

[[5 6 7]]


In [34]:
print(x1[1:])

[[5 6 7 8]]


In [38]:
print(x1[1:,0:3:1])
print(x1[1:,0:3:2])
print(x1[1:,0:3:3])

[[5 6 7]]
[[5 7]]
[[5]]


In [39]:
print(x1[0:2,2])

[3 7]


In [40]:
import numpy as np
x1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(x1[0:2,0:2,0:2])

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [41]:
print(x1.shape)

(2, 2, 3)


In [42]:
import numpy as np
x=np.array([1,2,3,4,5],ndmin=5)
print(x)
print(x.ndim)
print(x.shape)

[[[[[1 2 3 4 5]]]]]
5
(1, 1, 1, 1, 5)


In [43]:
import numpy as np
x=np.array([1,2,3,4,5])
new=x.reshape(2,3)
print(new)

ValueError: cannot reshape array of size 5 into shape (2,3)

In [44]:
import numpy as np
x=np.array([1,2,3,4,5])
new=x.reshape(5,1)
print(new)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [45]:
import numpy as np
x=np.array([1,2,3,4,5,6])
new=x.reshape(2,3).base
print(new)

[1 2 3 4 5 6]


In [46]:
import numpy as np
x=np.array([1,2,3,4,5,6])
new=x.reshape(2,-1)
print(new)

[[1 2 3]
 [4 5 6]]


In [47]:
import numpy as np
x=np.array([1,2,3,4,5,6])
new=x.reshape(-1,3)
print(new)

[[1 2 3]
 [4 5 6]]


In [50]:
import numpy as np
x1=np.array([[1,2,3,4],[5,6,7,8]])
for i in x1:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8


In [53]:
import numpy as np
x1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(x1):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [54]:
import numpy as np
x1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(x1[:,:,::2]):
    print(i)

1
3
4
6
7
9
10
12


In [55]:
import numpy as np
x1=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in np.nditer(x1[:,::2]):
    print(i)

1
2
3
7
8
9
