### 1. concatenate()

In [1]:
import numpy as np
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([7,8,9])
a=np.concatenate((a1,a2,a3))
print(a)

[1 2 3 4 5 6 7 8 9]


In [2]:
import numpy as np
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
a=np.concatenate((a1,a2))
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [3]:
import numpy as np
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
a=np.concatenate((a1,a2),axis=0)
print(a)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
import numpy as np
a1=np.array([[1,2],[3,4]])
a2=np.array([[5,6],[7,8]])
a=np.concatenate((a1,a2),axis=1)
print(a)

[[1 2 5 6]
 [3 4 7 8]]


### 2. array_split()

In [5]:
import numpy as np
a1=np.array([1,2,3,4])
new=np.array_split(a1,4)
print(new)

[array([1]), array([2]), array([3]), array([4])]


In [6]:
import numpy as np
a1=np.array([1,2,3,4])
new=np.array_split(a1,2)
print(new)

[array([1, 2]), array([3, 4])]


In [8]:
import numpy as np
a1=np.array([[1,2],[3,4],[5,6],[7,8]])
new=np.array_split(a1,4)
print(new)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [9]:
import numpy as np
a1=np.array([[1,2],[3,4],[5,6],[7,8]])
new=np.array_split(a1,3)
print(new)

[array([[1, 2],
       [3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [10]:
import numpy as np
a1=np.array([[1,2],[3,4],[5,6],[7,8]])
new=np.array_split(a1,4,axis=1)
print(new)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32), array([], shape=(4, 0), dtype=int32)]


In [11]:
import numpy as np
a1=np.array([[1,2],[3,4],[5,6],[7,8]])
new=np.array_split(a1,3,axis=1)
print(new)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]]), array([], shape=(4, 0), dtype=int32)]


### 3. where() : finds index

In [12]:
import numpy as np
a1=np.array([1,2,3,4,5,4,6,4,3])
x=np.where(a1==4)
print(x)

(array([3, 5, 7], dtype=int64),)


In [13]:
import numpy as np
a1=np.array([[1,2],[3,4],[5,4],[6,4]])
x=np.where(a1==4)
print(x)

(array([1, 2, 3], dtype=int64), array([1, 1, 1], dtype=int64))


In [14]:
import numpy as np
a1=np.array([[[1,2,3],[4,5,6]],[[4,8,9],[10,4,12]]])
x=np.where(a1==4)
print(x)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64), array([0, 0, 1], dtype=int64))


In [15]:
import numpy as np
a1=np.array([[1,2],[3,4],[5,4],[6,4]])
x=np.where(a1%2==0)
print(x)

(array([0, 1, 2, 3, 3], dtype=int64), array([1, 1, 1, 0, 1], dtype=int64))


### 4. sort()

In [16]:
import numpy as np
a1=np.array([1,2,4,3,6,5,2])
print(np.sort(a1))

[1 2 2 3 4 5 6]


In [21]:
import numpy as np
a1=np.array([1,2,4,3,6,5,2])
print(np.sort(a1,axis=-1))

[1 2 2 3 4 5 6]


In [22]:
import numpy as np
a1=np.array([1,2,4,3,6,5,2])
print(np.sort(a1,axis=0))

[1 2 2 3 4 5 6]


In [19]:
a2=np.array(['banana','apple','cherry','strawberry'])
print(np.sort(a2))

['apple' 'banana' 'cherry' 'strawberry']


In [20]:
a3=np.array([True,False,True])
print(np.sort(a3))

[False  True  True]


In [24]:
import numpy as np
a1=np.array([[3,4,2],[1,7,2],[4,2,5]])
print(np.sort(a1))

[[2 3 4]
 [1 2 7]
 [2 4 5]]


In [25]:
import numpy as np
a1=np.array([[3,4,2],[1,7,2],[4,2,5]])
print(np.sort(a1,axis=2))

AxisError: axis 2 is out of bounds for array of dimension 2

In [26]:
import numpy as np
a1=np.array([[3,4,2],[1,7,2],[4,2,5]])
print(np.sort(a1,axis=0))

[[1 2 2]
 [3 4 2]
 [4 7 5]]


In [29]:
import numpy as np
a1=np.array([[3,4,2],[1,7,2],[4,2,5]])
print(np.sort(a1,axis=-1)) #same for axis=1

[[2 3 4]
 [1 2 7]
 [2 4 5]]


In [30]:
import numpy as np
a1=np.array([[3,4,2],[1,7,2],[4,2,5]])
print(np.sort(a1,axis=None))

[1 2 2 2 3 4 4 5 7]


In [31]:
import numpy as np
a1=np.array([[[3,4,2],[1,7,2]],[[4,2,5],[8,2,4]]])
print(np.sort(a1))

[[[2 3 4]
  [1 2 7]]

 [[2 4 5]
  [2 4 8]]]


In [32]:
import numpy as np
a1=np.array([[[3,4,2],[1,7,2]],[[4,2,5],[8,2,4]]])
print(np.sort(a1,axis=2)) # same for axis=-1

[[[2 3 4]
  [1 2 7]]

 [[2 4 5]
  [2 4 8]]]


In [33]:
import numpy as np
a1=np.array([[[3,4,2],[1,7,2]],[[4,2,5],[8,2,4]]])
print(np.sort(a1,axis=1))

[[[1 4 2]
  [3 7 2]]

 [[4 2 4]
  [8 2 5]]]


In [35]:
import numpy as np
a1=np.array([[[3,4,2],[1,7,2]],[[4,2,5],[8,2,4]]])
print(np.sort(a1,axis=0))

[[[3 2 2]
  [1 2 2]]

 [[4 4 5]
  [8 7 4]]]


In [37]:
from numpy import random
x=random.randint(100)
print(x) # 0 to 99 only [0,100)

66


In [38]:
from numpy import random
x=random.randint(1,100,size=(5))
print(x)

[ 1  9 52  4 62]


In [39]:
from numpy import random
x=random.randint(1,100,size=(3,5))
print(x)

[[20 94 58 86 72]
 [62 80 74 22 27]
 [83 27 18 64  7]]


In [40]:
from numpy import random
x=random.randint(1,100,size=(2,2,3))
print(x)

[[[25 23 50]
  [21 70 64]]

 [[84 12 96]
  [44 90 77]]]


In [41]:
from numpy import random
x=random.rand()
print(x)

0.8424362490627983


In [42]:
from numpy import random
x=random.rand(5)
print(x)

[0.15378062 0.57005689 0.31544283 0.61031653 0.0012191 ]


In [43]:
from numpy import random
x=random.rand(3,5)
print(x)

[[0.86903813 0.12741515 0.72276265 0.00140357 0.69840402]
 [0.38023291 0.34993065 0.54945726 0.20401269 0.25432652]
 [0.54751304 0.38995036 0.6845692  0.87327435 0.13770872]]


In [45]:
from numpy import random
x=random.choice([1,3,5,7,9])
print(x)

5


In [46]:
from numpy import random
x=random.choice([1,3,5,7,9],size=(5))
print(x)

[1 3 9 7 7]


In [48]:
from numpy import random
x=random.randint(100)
def guess():
    attempt=7
    i=0
    while(i!=7):
        n=int(input("Enter a number between 1 to 100: "))
        if n==x:
            print("You won!")
        else:
            attempt=attempt-1
            print("attempt left = ",attempt)
            i+=1
            if attempt==0:
                print("You lost")
                print("Correct nnumber was : ",x)
guess()

Enter a number between 1 to 100: 45
attempt left =  6
Enter a number between 1 to 100: 30
attempt left =  5
Enter a number between 1 to 100: 1
attempt left =  4
Enter a number between 1 to 100: 22
attempt left =  3
Enter a number between 1 to 100: 89
attempt left =  2
Enter a number between 1 to 100: 44
attempt left =  1
Enter a number between 1 to 100: 90
attempt left =  0
You lost
Correct nnumber was :  84


In [1]:
from numpy import random
x=random.randint(100)
def guess():
    attempt=7
    i=0
    while(i!=7):
        n=int(input("Enter a number between 1 to 100: "))
        if n==x:
            print("You won!")
            break
        else:
            if(x>n):
                print("Guess a higher number")
            else:
                print("guess a lower number")
            attempt=attempt-1
            print("attempt left = ",attempt)
            i+=1
            if attempt==0:
                print("You lost")
                print("Correct nnumber was : ",x)
guess()

Enter a number between 1 to 100: 50
Guess a higher number
attempt left =  6
Enter a number between 1 to 100: 90
guess a lower number
attempt left =  5
Enter a number between 1 to 100: 75
guess a lower number
attempt left =  4
Enter a number between 1 to 100: 65
guess a lower number
attempt left =  3
Enter a number between 1 to 100: 58
Guess a higher number
attempt left =  2
Enter a number between 1 to 100: 62
guess a lower number
attempt left =  1
Enter a number between 1 to 100: 60
You won!
